name: vaca

services:
  frontend:
    build:
      context: vaca-frontend
      target: prod
    ports:
      - "80:8080"
      - "3001:3001"
  api:
    build: ./vaca-api
    volumes:
      - ./secrets:/app/api/secrets
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    build: db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  db_data:
